apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.inclusions: |
    - apiGroups:
        - ""
        - apps
      kinds:
        - ConfigMap
        - Deployment
      