apiVersion: v1
data:
  service.webhook.github: |
    url: https://api.github.com
    headers: #optional headers
    - name: Authorization
      value: $pat-github
  service.webhook.argo-workflow: |
    url: http://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows/argo
    headers: #optional headers
    - name: Content-Type
      value: application/json
  template.github-action: |
    webhook:
      github:
        method: POST
        path: /repos/devopsYo/apigee/actions/workflows/{{ .Values.github.workflowFileName }}/dispatches
        body: |
          {
            "ref": "main",
            "inputs": {
              "swagger_app_name": "{{ .Values.swagger_app_name }}"
            }
          }
  template.argo-workflow-submit: |
    webhook:
      argo-workflow:
        method: POST
        body: |
          {
            "namespace": "argo",
            "workflow": {
              "metadata": {
                "generateName": "post-deploy-github-action-template-",
                "namespace": "argo",
                "labels": {
                  "workflows.argoproj.io/workflow-template": "post-deploy-github-action-template"
                }
              },
              "spec": {
                "workflowTemplateRef": {
                  "name": "post-deploy-github-action-template"
                },
                "arguments": {
                  "parameters": [
                    {
                      "name": "app-name",
                      "value": "{{ .app.metadata.name }}"
                    }
                  ]
                }
              }
            }
          }
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send: [github-action, argo-workflow-submit]
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
kind: ConfigMap
metadata:
  name: cmdo-argocd-notifications-cm
