apiVersion: v1
data:
  service.webhook.github: |
    url: https://api.github.com
    headers: #optional headers
    - name: Authorization
      value: $pat-github
  template.github-action: |
    webhook:
      github:
        method: POST
        path: /repos/devopsYo/apigee/actions/workflows/{{ .Values.github.workflowFileName }}/dispatches
        body: |
          {
            "event_type": "webhook",
            "client_payload": {
                "unit": false,
                "integration": true
            }
          }
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send: [app-sync-succeeded, github-action]
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
kind: ConfigMap
metadata:
  name: cmdo-argocd-notifications-cm
