apiVersion: v1
data:
  service.webhook.github: |
    url: https://api.github.com
    headers: #optional headers
    - name: Authorization
      value: $pat-github
  template.github-action: |
    webhook:
      github:
        method: POST
        path: /repos/devopsYo/apigee/actions/workflows/{{ .Values.github.workflowFileName }}/dispatches
        body: |
          {
            "ref": "main",
            "inputs": {
              "swagger_app_name": {{ .Values.swagger_app_name }}
            }
          }
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send: [app-sync-succeeded, github-action]
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
kind: ConfigMap
metadata:
  name: cmdo-argocd-notifications-cm
